# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ closed ]

env:
  name: Anatol

jobs:
  
  build:
    runs-on: ubuntu-latest
    env:
      name: ant0lik

    steps:
   
      - name: Run a one-line script
        run: echo Hello, $name!

  pull_request_only:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: github.event_name == 'pull-request'
    needs: build

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

